export const blogsCardData = [
  {
    title: "Top Market Research Companies in the UAE for Startups",
    subtitle: "Unraveling practicality",
    description:
      "Ever wondered how ideas transform into successful business projects?",
    bg: "/card1.webp",
    link: "/blogs/top-market-research-companies-in-the-uae-for-startups",
  },
  {
    title: "How Mastering Storytelling Improves Qualitative Market Research Insights?",
    subtitle: "Marketing approach",
    description: "The key to turning raw data into a compelling narrative",
    bg: "/card2.webp",
    link: "/blogs/how-mastering-storytelling-improves-qualitative-market-research-insights",
  },
  {
    title: "The Importance of Brand Strategy for Entrepreneurs & Startups in Dubai",
    subtitle: "Employee Satisfaction",
    description: "Customer Experience And Happiness",
    bg: "/card3.webp",
    link: "/blogs/the-importance-of-brand-strategy-for-entrepreneurs-startups-in-dubai",
  },
  {
    title: "Unleashing the Power of Brand Tracking for Your Business Success",
    subtitle: "Master The Data",
    description: "Performance monitoring",
    bg: "/card3.webp",
    link: "/blogs/unleashing-the-power-of-brand-tracking-for-your-business-success",
  },
  {
    title: "How Market Research for the Pharma Industry Unlocks Explosive Growth",
    subtitle: "Faster decisions",
    description: "The collection and analysis of business information",
    bg: "/card2.webp",
    link: "/blogs/how-market-research-for-the-pharma-industry-unlocks-explosive-growth",
  },
  {
    title: "Brand Strategy Benefits for Small Businesses: How to Build a Strong Identity",
    subtitle: "In-depth process",
    description: "Insights to facilitate informed decision-making",
    bg: "/card1.webp",
    link: "/blogs/brand-strategy-benefits-for-small-businesses-how-to-build-a-strong-identity",
  },
  {
    title: "How to Select the Best Market Research Method for Your Project: A Complete Guide",
    subtitle: "Digital transformation",
    description: "A strategic approach to leverage its full potential",
    bg: "/card1.webp",
    link: "/blogs/how-to-select-the-best-market-research-method-for-your-project-a-complete-guide",
  },
  {
    title: "Unlocking the Power of Tableau: Transform Your Data into Insights",
    subtitle: "Thought Leadership",
    description: "Helping organizations retain customers and build loyalty",
    bg: "/card1.webp",
    link: "/blogs/unlocking-the-power-of-tableau-transform-your-data-into-insights",
  },
  {
    title: "The Ultimate Guide to Microsoft Power BI: Elevate Your Data Visualization Skills",
    subtitle: "Thought Leadership",
    description: "Helping organizations retain customers and build loyalty",
    bg: "/card1.webp",
    link: "/blogs/the-ultimate-guide-to-microsoft-power-bi-elevate-your-data-visualization-skills",
  },
];
